### ISSUE TITLE
How to go back stock kernel

### ISSUE THREAD

**Issue by Jrmewam** [NotZeetaa/YAKT#10]
Thanks for this work. If I wanna try it but then want to go back to stock kernel;

would uninstalling the magisk module wipe it and set back stock settings?

**Comment by NotZeetaa** [comment]
> Thanks for this work. If I wanna try it but then want to go back to stock kernel;
> 
> would uninstalling the magisk module wipe it and set back stock settings?

Thank you, just remove magisk module and reboot
Thats it.

**Comment by Jrmewam** [comment]
Couldn't be any more simple :)
Thanks!

**Comment by NotZeetaa** [comment]
> Couldn't be any more simple :) Thanks!

Enjoy :)
