### ISSUE TITLE
Version problem in Magisk Repository

### ISSUE THREAD

**Issue by giving-sesame** [NotZeetaa/YAKT#11]
Hi! To manage Magisk modules I use Fox's Magisk Module Manager https://github.com/Fox2Code/FoxMagiskModuleManager
This Manager looks for modules in different repositories. And it suggests to install your module of version 2 only. I spotted one bug there, came to your page to report it and found out that there is a new version where this bug was corrected.

Could you please check the repository where your module is present, so it distributes the actual version, not outdated?

**Comment by NotZeetaa** [comment]
> Hi! To manage Magisk modules I use Fox's Magisk Module Manager https://github.com/Fox2Code/FoxMagiskModuleManager This Manager looks for modules in different repositories. And it suggests to install your module of version 2 only. I spotted one bug there, came to your page to report it and found out that there is a new version whether this bug was corrected.
> 
> Could you please check the repository where your module is present, so it distribute the actual version, not outdated?

Yhea that's my bad cause i still didn't updated the source in other repo

**Comment by giving-sesame** [comment]
Thank you!
