### ISSUE TITLE
Log file not found

### ISSUE THREAD

**Issue by some1onLSD** [NotZeetaa/YAKT#12]
Hello,
I did as the guide said and flashed it in magisk and rebooted, when the reboot was done I checked the internal storage for log but I couldn't find it.

**Comment by NotZeetaa** [comment]
Hello, Do u use any other modules?

**Comment by some1onLSD** [comment]
Hi,
Thanks for the quick response 
Here's a screenshot of my modules

![Screenshot_20220827-232340_Magisk](https://user-images.githubusercontent.com/74503778/187050018-49ff0399-550d-4588-9719-a7c2d63ca689.png)

**Comment by NotZeetaa** [comment]
> Hi, Thanks for the quick response Here's a screenshot of my modules
> 
> ![Screenshot_20220827-232340_Magisk](https://user-images.githubusercontent.com/74503778/187050018-49ff0399-550d-4588-9719-a7c2d63ca689.png)

Can you tell which android version are you running on?

**Comment by some1onLSD** [comment]
Android Version 12 (Corvus OS Official)

![Screenshot_20220827-232934_Settings](https://user-images.githubusercontent.com/74503778/187050192-08cc1e54-30de-4dcf-b90f-9cb1d7297e61.png)

**Comment by NotZeetaa** [comment]
> Android Version 12 (Corvus OS Official)
> 
> ![Screenshot_20220827-232934_Settings](https://user-images.githubusercontent.com/74503778/187050192-08cc1e54-30de-4dcf-b90f-9cb1d7297e61.png)

Can u try disable  NotStorageRestrict and Systemless Hosts?

**Comment by some1onLSD** [comment]
I'll try to do it and get back to you..

**Comment by some1onLSD** [comment]
Okay this is weird I disabled them and the log file is there now, then I deleted the log file and enabled them again and the log file showed up too... that's strange.

But anyway I wanted to ask you about the things that aren't supported by my kernel (UFS Turbo, mglru, kprofiles, watermark boost) how can I enable them??

**Comment by NotZeetaa** [comment]
> Okay this is weird I disabled them and the log file is there now, then I deleted the log file and enabled them again and the log file showed up too... that's strange.
> 
> But anyway I wanted to ask you about the things that aren't supported by my kernel (UFS Turbo, mglru, kprofiles, watermark boost) how can I enable them??

Good.
You will need to ask your kernel dev to add support to it
