### ISSUE TITLE
Please use Logs instead of Documents path

### ISSUE THREAD

**Issue by Enkidu70** [NotZeetaa/YAKT#14]
If there is already a Logs directory, YAKT should use this one instead of Documents.

Tnx in advance.

**Comment by NotZeetaa** [comment]
Can you be more specific with logs directory?

**Comment by Enkidu70** [comment]
Currently, log is saved to /sdcard/Documents/yakt.<br>
Better would be, please save logs to /sdcard/Logs/yakt if Logs directory is present.

**Comment by NotZeetaa** [comment]
> Currently, log is saved to /sdcard/Documents/yakt. Better would be, please save logs to /sdcard/Logs/yakt if Logs directory is present.

That makes sense but i don't have that dir, some module u installed and created that Logs dir. And Documents folder makes more sense IMO.

**Comment by Enkidu70** [comment]
It is a simple if-clause to look if Logs is there. If so, please use it. Otherwise use Documents.

On my device I use Documents for real documents, not for debugging stuff... Also other dev-apps like Matlog ecc. use Logs directory. Because it makes sense...

**Comment by Enkidu70** [comment]
You could change yaks.sh like that:

```
if [ -d /sdcard/Logs ]; then
  LOG=/sdcard/Logs/yakt.log
  if [ ! -d $LOG ]; then
    mkdir $LOG
  fi
elif [ ! -d /sdcard/Documents ]; then
  LOG=/sdcard/yakt.log
else
  if [ ! -d /sdcard/Documents/yakt ]; then
    mkdir /sdcard/Documents/yakt
    LOG=/sdcard/Documents/yakt/yakt.log
  else
    LOG=/sdcard/Documents/yakt/yakt.log
  fi
fi
```

**Comment by Enkidu70** [comment]
Above a better idea of setting up log
