### ISSUE TITLE
Host files on GitHub

### ISSUE THREAD

**Issue by lefuglyduck** [NotZeetaa/YAKT#24]
Please. "Pling" and "opendesktop.org" are diseased cesspools of ads. It takes something like 10 clicks (exaggerating, but still) to get to the file.

**Comment by lefuglyduck** [comment]
Thanks, I guess that sort of begs the question of why? Why did you create the zip on that manner? Why not make it immediately flashable?

**Comment by NotZeetaa** [comment]
Hey @lefuglyduck ,
Sorry for the late reply, but the reason for the challenging zip download is because those peculiar ads and such are meant to support the developer. In the next update, I will reduce them, thank you.

**Comment by chengnan049** [comment]
> Hey @lefuglyduck ,
> Sorry for the late reply, but the reason for the challenging zip download is because those peculiar ads and such are meant to support the developer. In the next update, I will reduce them, thank you.

I think it's a reasonable, but on my device it detects my adblocker and even if I turn it all off I can't download it, this has been happening for a few months now

**Comment by NotZeetaa** [comment]
Gonna close this issue cause i won't host files anymore on devuploads and i believe that was ur issue, thank you.
